# Generated by Django 5.2.7 on 2025-12-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('pasien', 'Pasien'), ('dokter', 'Dokter'), ('admin_sistem', 'Admin Sistem'), ('admin_poliklinik', 'Admin Poliklinik'), ('admin', 'Admin')], default='pasien', max_length=20),
        ),
    ]
