# Generated by Django 5.2.7 on 2025-11-28 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Konten')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Gambar')),
                ('excerpt', models.TextField(blank=True, help_text='Ringkasan artikel (opsional)', max_length=300)),
                ('is_published', models.BooleanField(default=True, verbose_name='Diterbitkan')),
                ('views_count', models.IntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Penulis')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-created_at'],
            },
        ),
    ]
