# Generated by Django 5.2.7 on 2025-11-28 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Paket Pemeriksaan Umum'), ('women', 'Kesehatan Wanita'), ('child', 'Kesehatan Anak'), ('heart', 'Jantung & Pembuluh Darah'), ('immunity', 'Imunitas & Infeksi')], default='general', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('preparation', models.CharField(blank=True, help_text='Persiapan sebelum pemeriksaan. Contoh: Puasa 8 jam.', max_length=255)),
                ('sample_type', models.CharField(blank=True, max_length=100)),
                ('result_time', models.CharField(default='2-3 Hari Kerja', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_package', models.BooleanField(default=False)),
                ('included_tests', models.TextField(blank=True, help_text='Daftar tes yang termasuk (jika paket).')),
                ('icon', models.CharField(blank=True, help_text='Nama ikon (misal: bi-droplet).', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('fasting_confirmation', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Sudah Dikonfirmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='laboratory.labservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
