# Generated by Django 5.2.7 on 2025-11-26 07:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Obat')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosis')),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('kapsula', 'Kapsula'), ('mL', 'Mililiter'), ('gram', 'Gram'), ('botol', 'Botol')], max_length=20, verbose_name='Satuan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Harga')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stok')),
                ('side_effects', models.TextField(blank=True, verbose_name='Efek Samping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medicines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Pesanan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi'), ('processing', 'Sedang Diproses'), ('ready', 'Siap Dikirim'), ('shipped', 'Dalam Pengiriman'), ('delivered', 'Terkirim'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_address', models.TextField(verbose_name='Alamat Pengiriman')),
                ('delivery_phone', models.CharField(max_length=15, verbose_name='Nomor Telepon Pengiriman')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Pesanan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Menunggu Pengantar'), ('in_transit', 'Dalam Pengiriman'), ('delivered', 'Terkirim'), ('failed', 'Pengiriman Gagal')], default='waiting', max_length=20)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude Apotek')),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude Apotek')),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude Tujuan')),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude Tujuan')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Tiba')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Tiba Aktual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='pharmacy.medicineorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.medicineorder')),
            ],
            options={
                'unique_together': {('order', 'medicine')},
            },
        ),
    ]
