# Generated by Django 5.2.7 on 2025-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude Pengiriman'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude Pengiriman'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diterima'),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi'), ('processing', 'Sedang Diproses'), ('ready', 'Siap Dikirim'), ('shipped', 'Dalam Pengiriman'), ('delivered', 'Terkirim'), ('received', 'Diterima Pasien'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
