# Generated by Django 5.2.7 on 2025-12-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicineorder_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payments/orders/'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum Bayar'), ('pending', 'Menunggu Verifikasi'), ('paid', 'Lunas'), ('failed', 'Gagal')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
