# Generated by Django 5.2.7 on 2025-11-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_24h', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['priority', 'label'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('hospital', 'Rumah Sakit'), ('puskesmas', 'Puskesmas')], default='hospital', max_length=20)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=30)),
                ('ambulance_number', models.CharField(blank=True, max_length=30)),
                ('emergency_unit', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['facility_type', 'name'],
            },
        ),
    ]
