# Generated by Django 5.2.7 on 2025-11-28 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0004_alter_doctor_email_alter_doctor_user'),
        ('poliklinik', '0002_delete_dokter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Menunggu'), ('checked_in', 'Sudah Check In'), ('in_progress', 'Sedang Dilayani'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_time', models.IntegerField(default=0, help_text='Estimasi waktu tunggu dalam menit')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL)),
                ('poliklinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='poliklinik.poliklinik')),
            ],
            options={
                'ordering': ['queue_number'],
            },
        ),
    ]
