# Generated by Django 5.2.7 on 2025-11-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poliklinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('force_open', models.BooleanField(default=False)),
                ('force_close', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('poliklinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokters', to='poliklinik.poliklinik')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('poliklinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='poliklinik.poliklinik')),
            ],
        ),
    ]
