# Generated by Django 5.2.7 on 2025-11-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('poliklinik', '0002_delete_dokter'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='poliklinik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='poliklinik.poliklinik'),
        ),
    ]
