# Generated by Django 5.2.7 on 2025-12-18 15:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultation_options_consultation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='consultation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payments/consultation/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum Bayar'), ('pending', 'Menunggu Konfirmasi'), ('paid', 'Lunas'), ('failed', 'Gagal')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
